name: Master

on:
  push:
    branches: [ master ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads=1

  deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ezzizzle/uploadserver
        tags: latest
        tag_with_sha: true
