name: Master

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ezzizzle/uploadserver
        tags: latest
        tag_with_sha: true
